services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: POO_ADVANCED
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/creation_script.sql:/docker-entrypoint-initdb.d/01_creation_script.sql
      - ./mysql/Preremplissage.sql:/docker-entrypoint-initdb.d/02_preremplissage.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  mysql_data: